server:
  port: 30000

spring:
  application:
    name: zhengdanmall-third-party
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848


logging:
  level:
    io.niceseason.gulimall.product: debug

