spring:
  datasource:
    username: root
    password: 2333
    url: jdbc:mysql://192.168.30.128:3306/zhengdanmall_pms
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: zhengdanmall-product

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      #主键自增
      id-type: auto

server:
  port: 10001

logging:
  level:
    com.ufo.zhengdanmall.product: debug
